In [43]:
import numpy as np 

# Q1: Write a code to combine  a one and a two-dimensional NumPy Array




In [44]:
#append( )is used to connect a new datafrfame to the end of a given dataframe, returning a new dataframe object



l = np.array([1,2,3,4])   # create numpy array
print(l)                  # view array
m = [[0,2,4,8], [6,10,12,18]]  # create numpy array 
print(m)                   # view array
for a, b in np.nditer([x,y]):
    print("%d:%d" % (a,b),)   



[1 2 3 4]
[[0, 2, 4, 8], [6, 10, 12, 18]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


# Q. 2. Write a code to check whether a Numpy array contains a specified row. 

In [45]:
# importing package
import numpy


arr = numpy.array([[1, 2, 3, 4, 5],   # create numpy array
                [6, 7, 8, 9, 10],
                [11, 12, 13, 14, 15]
                ])
print(arr)  # view array

# check for some lists
print([1, 2, 3, 4, 5] in arr.tolist())
print([16, 17, 25, 19, 20] in arr.tolist())
print([3, 2, -5, -4, 45] in arr.tolist())
print([11, 12, 13, 14, 15] in arr.tolist())



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
True
False
False
True


# Q. 3.  Write a Pandas code to create and display a DataFrame from a specified dictionary data which has the index labels

In [46]:
import pandas as pd

In [47]:
#Creating dataframe from dictionary
d1 = {" Name" : "John",
      "Age" :10, 
      "Class" : 1  
     }
# Create the pandas DataFrame
dfz = pd.DataFrame(d1,index = ["Details"])
# print dataframe.
print(dfz)

         Name  Age  Class
Details  John   10      1


# Q. 4.Write a pandas code to create DataFrame from dict of narray/lists

In [48]:
#Creating dataframe from dictionary of lists

data1 = {
  "distance": [500, 450, 350],
  "speed": [60, 40, 55]
}

#load data into a DataFrame object:

df = pd.DataFrame(data1, index = ["car1","car2", "car3"])
# print dataframe.
print(df)

      distance  speed
car1       500     60
car2       450     40
car3       350     55


# Q. 5. Write a pandas code to create Pandas dataframe using list of lists

In [49]:
 
# initialize list of lists
data = [['Universe', 'R&B', 'LOOΠΔ/'], ['Pale bule dot', 'Euphoria', 'LOOΠΔ/'], ['Playback', 'Metal', 'LOOΠΔ/'],
        ['Oops', 'Rock', 'LOOΠΔ/'], ['F!ip That', 'Dreamy', 'LOOΠΔ/'], ['New', 'R&B', 'LOOΠΔ/'], ]
 
# Create the pandas DataFrame
df = pd.DataFrame(data, columns = ['Song Name', 'Genere', 'Singer'])
 
# print dataframe.
print(df )

       Song Name    Genere  Singer
0       Universe       R&B  LOOΠΔ/
1  Pale bule dot  Euphoria  LOOΠΔ/
2       Playback     Metal  LOOΠΔ/
3           Oops      Rock  LOOΠΔ/
4      F!ip That    Dreamy  LOOΠΔ/
5            New       R&B  LOOΠΔ/
